on:
  workflow_dispatch:
    inputs:
      target:      { type: string, required: true }
      pr_number:   { type: string, required: true }
      head_sha:   { type: string, required: true }

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: per-item-${{ inputs.target }}-${{ github.sha }}
  cancel-in-progress: false

jobs:
  work:
    runs-on: ubuntu-latest
    steps:
      - id: checkrun
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          CHECKID=$(gh api -X POST -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f name='Super Check' \
            -f head_sha='${{ inputs.head_sha }}' \
            -f status='queued' \
            -f 'output[title]=My Check Run Title' \
            -f 'output[summary]=A *fancy* summary' \
            -f 'output[text]=More detailed Markdown **text**' \
            --jq '.id' \
            /repos/${{ github.repository }}/check-runs)

          echo "checkId=$CHECKID" >> $GITHUB_OUTPUT

      - run: echo "🔧 Working on ${{ inputs.target }} for PR ${{ inputs.pr_number }}"
      - run: sleep 10

      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api -X PATCH -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/check-runs/${{ steps.checkrun.outputs.checkId }} \
            --input - <<- EOF
            {
              "conclusion": "success",
              "details_url": "https://google.com",
              "output": {
                "title": "My Check Run Title 🚀",
                "summary": "**Summary**: The run completed.",
                "text": "Everything worked as expected. You should see a logo above."
               }
            }
          EOF
